// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qCP8p-EiRXc2CEbxbrQoLLYyHiMfeK4',
    appId: '1:696920631745:web:1d70db788085c8fe10e740',
    messagingSenderId: '696920631745',
    projectId: 'smartumrah-a58c2',
    authDomain: 'smartumrah-a58c2.firebaseapp.com',
    storageBucket: 'smartumrah-a58c2.firebasestorage.app',
    measurementId: 'G-DKM5HC56CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyfyy9ptTscH1Rzj3Eskc_7EJ4QMlWhPs',
    appId: '1:696920631745:android:470b815dbcc7361c10e740',
    messagingSenderId: '696920631745',
    projectId: 'smartumrah-a58c2',
    storageBucket: 'smartumrah-a58c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAolb7-1YV7LWpK5USKJ8dh5frASLjB96I',
    appId: '1:696920631745:ios:f4891f1d724e7c2610e740',
    messagingSenderId: '696920631745',
    projectId: 'smartumrah-a58c2',
    storageBucket: 'smartumrah-a58c2.firebasestorage.app',
    iosBundleId: 'com.example.smartUmrahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAolb7-1YV7LWpK5USKJ8dh5frASLjB96I',
    appId: '1:696920631745:ios:f4891f1d724e7c2610e740',
    messagingSenderId: '696920631745',
    projectId: 'smartumrah-a58c2',
    storageBucket: 'smartumrah-a58c2.firebasestorage.app',
    iosBundleId: 'com.example.smartUmrahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9qCP8p-EiRXc2CEbxbrQoLLYyHiMfeK4',
    appId: '1:696920631745:web:cd0c7daaf2b12f7410e740',
    messagingSenderId: '696920631745',
    projectId: 'smartumrah-a58c2',
    authDomain: 'smartumrah-a58c2.firebaseapp.com',
    storageBucket: 'smartumrah-a58c2.firebasestorage.app',
    measurementId: 'G-F6PVB4KGME',
  );

}