// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxIY9lXJIwivA3BKdOI-iGztM5ng15sDw',
    appId: '1:13880865396:web:d01c9343c0fac7ab115721',
    messagingSenderId: '13880865396',
    projectId: 'umrahapp-7d068',
    authDomain: 'umrahapp-7d068.firebaseapp.com',
    storageBucket: 'umrahapp-7d068.firebasestorage.app',
    measurementId: 'G-B28JTGL9KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphN6l_G8runYeJ9gyPrKw--8Cyb2f-z8',
    appId: '1:13880865396:android:157c43efca3b8578115721',
    messagingSenderId: '13880865396',
    projectId: 'umrahapp-7d068',
    storageBucket: 'umrahapp-7d068.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3cxX9da7Qw1nSVW7-gbkxzCtUCc_Rl_A',
    appId: '1:13880865396:ios:e6c4e4f44b8b081f115721',
    messagingSenderId: '13880865396',
    projectId: 'umrahapp-7d068',
    storageBucket: 'umrahapp-7d068.firebasestorage.app',
    iosBundleId: 'com.example.smartUmrahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3cxX9da7Qw1nSVW7-gbkxzCtUCc_Rl_A',
    appId: '1:13880865396:ios:e6c4e4f44b8b081f115721',
    messagingSenderId: '13880865396',
    projectId: 'umrahapp-7d068',
    storageBucket: 'umrahapp-7d068.firebasestorage.app',
    iosBundleId: 'com.example.smartUmrahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxIY9lXJIwivA3BKdOI-iGztM5ng15sDw',
    appId: '1:13880865396:web:8d04e58ae8099023115721',
    messagingSenderId: '13880865396',
    projectId: 'umrahapp-7d068',
    authDomain: 'umrahapp-7d068.firebaseapp.com',
    storageBucket: 'umrahapp-7d068.firebasestorage.app',
    measurementId: 'G-3K873Y8D81',
  );

}